// Generated by https://quicktype.io

export interface ProgramGuideResponse {
    entry:    { [key: string]: string };
    response: ProgramGuide;
    status:   string;
    msg:      string;
}

export interface ProgramGuide {
    channels: Channel[];
    total:    number;
}

export interface Channel {
    id:                     string;
    number:                 string;
    name:                   string;
    hd:                     boolean;
    image:                  string;
    group_id:               string;
    liveref:                string;
    epg_url:                EpgURL;
    provider_metadata_id:   number;
    provider_metadata_name: ProviderMetadataName;
    group:                  Group;
    events:                 Event[];
}

export enum EpgURL {
    EpgURLTv = "tv",
    Tv = "TV",
}

export interface Event {
    channel_id:               string;
    id:                       string;
    name:                     Name;
    description:              null | string;
    talent:                   null;
    date_begin:               string;
    date_end:                 string;
    unix_begin:               number;
    unix_end:                 number;
    duration:                 string;
    language:                 null | string;
    type:                     null | string;
    group_id:                 null;
    confirmado:               null;
    id_empleado:              null;
    tms_id:                   null;
    event_alf_id:             null | string;
    ext_ncont_id:             null | string;
    ext_nevt_id:              null | string;
    ext_actors:               null;
    ext_director:             null;
    ext_year:                 null;
    ext_country:              null;
    ext_original_name:        Name | null;
    ext_ep_original_name:     null;
    ext_series_id:            null | string;
    ext_season_id:            null;
    ext_episode_id:           null | string;
    ext_language:             null | string;
    ext_serie_short_desc:     null;
    ext_serie_desc:           null;
    image_base_horizontal:    string;
    image_base_vertical:      string;
    image_base_square:        string;
    ext_eventimage_name:      string;
    ext_eventimage_name_base: string;
    ext_catchup:              null | string;
    ext_startover:            null | string;
    ext_recordable:           null | string;
    parental_rating:          null;
    aud_stereo:               null | string;
    aud_dolby:                null | string;
    vid_black_and_white:      null | string;
    dvb_content:              null | string;
    user_content:             null;
    group_rel:                null;
    gmt:                      number;
}

export enum Name {
    CierreDeTransmisión = "Cierre De Transmisión",
    Na = "NA",
}

export interface Group {
    common: Common;
}

export interface Common {
    id:                     string;
    title:                  string;
    title_episode:          null;
    title_uri:              string;
    title_original:         string;
    description:            string;
    description_large:      string;
    short_description:      null;
    image_large:            string;
    image_medium:           string;
    image_small:            string;
    image_still:            null;
    image_background:       string;
    url_imagen_t1:          string;
    url_imagen_t2:          string;
    image_base_horizontal:  string;
    image_base_vertical:    string;
    image_base_square:      string;
    image_clean_horizontal: string;
    image_clean_vertical:   string;
    image_clean_square:     string;
    image_sprites:          string;
    image_frames:           string;
    image_trickplay:        string;
    image_external:         null;
    duration:               null;
    date:                   DateEnum;
    year:                   null;
    preview:                string;
    season_number:          null;
    episode_number:         null;
    format_types:           FormatTypes;
    live_enabled:           string;
    live_type:              string;
    live_ref:               string;
    timeshift:              null;
    votes_average:          number;
    rating_code:            RatingCode;
    proveedor_name:         ProveedorName;
    proveedor_code:         ProveedorCode;
    encoder_tecnology:      Nology;
    recorder_technology:    Nology;
    resource_name:          null;
    rollingcreditstime:     null;
    rollingcreditstimedb:   null;
    is_series:              boolean;
    channel_number:         string;
}

export enum DateEnum {
    The15072020 = "15/07/2020",
    The20200612131656 = "20200612131656",
}

export interface Nology {
    id:   null | string;
    desc: Desc | null;
}

export enum Desc {
    HarmonicVos = "HARMONIC_VOS",
}

export enum FormatTypes {
    Free = "free",
    Susc = "susc",
}

export enum ProveedorCode {
    Amco = "amco",
    Cvperu = "cvperu",
}

export enum ProveedorName {
    Amco = "AMCO",
    ClaroVideoPeru = "CLARO VIDEO PERU",
}

export enum RatingCode {
    G = "G",
}

export enum ProviderMetadataName {
    Nagra = "NAGRA",
}
